import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="modulepreload" href="https://stunts.b-cdn.net/entropy-chat-d94bd7e2ee5724d1.js" crossOrigin="anonymous" integrity="sha384-IPf0Pk2uPVJGlzs6ehER77hdfGvz6KsFtH0Qn0uE7LNC/AqDmKIF0dx+wXTEWcMx"/><link rel="preload" href="https://stunts.b-cdn.net/entropy-chat-d94bd7e2ee5724d1_bg.wasm" crossOrigin="anonymous" integrity="sha384-3HsUuNZOoSd5WOAh+6GyzYRIQAx3D+hQJOWYIbFn3k/6slxOVgg0wQB0JhDiRayI" as="fetch" type="application/wasm"/>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
